-- AlterEnum LeadStatus (Add missing enum values to PostgreSQL pg_enum)
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'CALL_BACK';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'DETAILS_SENT';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'VISIT_SCHEDULED';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'VISIT_DONE';
