-- Additive payroll snapshot and delivery fields. Existing rows keep their values.
ALTER TABLE "PayrollItem" ADD COLUMN IF NOT EXISTS "payableDays" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "PayrollItem" ADD COLUMN IF NOT EXISTS "holidayDays" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "PayrollItem" ADD COLUMN IF NOT EXISTS "weeklyOffDays" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "PayrollItem" ADD COLUMN IF NOT EXISTS "lopDays" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "PayrollItem" ADD COLUMN IF NOT EXISTS "lopDeduction" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "PayrollItem" ADD COLUMN IF NOT EXISTS "advanceDeduction" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "PayrollItem" ADD COLUMN IF NOT EXISTS "paidAt" TIMESTAMP(3);
ALTER TABLE "PayrollItem" ADD COLUMN IF NOT EXISTS "emailStatus" TEXT NOT NULL DEFAULT 'EMAIL_PENDING';
ALTER TABLE "PayrollItem" ADD COLUMN IF NOT EXISTS "whatsappStatus" TEXT NOT NULL DEFAULT 'WHATSAPP_PENDING';
ALTER TABLE "PayrollItem" ADD COLUMN IF NOT EXISTS "calculationSnapshot" JSONB;
