-- AlterEnum
ALTER TYPE "WorkStatus" ADD VALUE IF NOT EXISTS 'ASSIGNED';
ALTER TYPE "WorkStatus" ADD VALUE IF NOT EXISTS 'PROCESSING';
ALTER TYPE "WorkStatus" ADD VALUE IF NOT EXISTS 'SUBMITTED';
ALTER TYPE "WorkStatus" ADD VALUE IF NOT EXISTS 'CUSTOMER_REVIEW';
ALTER TYPE "WorkStatus" ADD VALUE IF NOT EXISTS 'REVISION_REQUESTED';
ALTER TYPE "WorkStatus" ADD VALUE IF NOT EXISTS 'APPROVED';

-- AlterEnum
ALTER TYPE "WorkType" ADD VALUE IF NOT EXISTS 'REEL';
ALTER TYPE "WorkType" ADD VALUE IF NOT EXISTS 'CREATIVE_POST';
ALTER TYPE "WorkType" ADD VALUE IF NOT EXISTS 'STORY';
ALTER TYPE "WorkType" ADD VALUE IF NOT EXISTS 'INFLUENCER_PROMOTION';
ALTER TYPE "WorkType" ADD VALUE IF NOT EXISTS 'GRAPHIC_DESIGN';
ALTER TYPE "WorkType" ADD VALUE IF NOT EXISTS 'VIDEO';
ALTER TYPE "WorkType" ADD VALUE IF NOT EXISTS 'SHOOT';
ALTER TYPE "WorkType" ADD VALUE IF NOT EXISTS 'EDITING';
ALTER TYPE "WorkType" ADD VALUE IF NOT EXISTS 'SOCIAL_MEDIA_MANAGEMENT';
ALTER TYPE "WorkType" ADD VALUE IF NOT EXISTS 'CONTENT_WRITING';
ALTER TYPE "WorkType" ADD VALUE IF NOT EXISTS 'META_ADS';
ALTER TYPE "WorkType" ADD VALUE IF NOT EXISTS 'GOOGLE_ADS';
ALTER TYPE "WorkType" ADD VALUE IF NOT EXISTS 'PERFORMANCE_REPORT';

-- AlterTable
ALTER TABLE "Work" ADD COLUMN IF NOT EXISTS "editorId" INTEGER;
ALTER TABLE "Work" ADD COLUMN IF NOT EXISTS "feedback" TEXT;
ALTER TABLE "Work" ADD COLUMN IF NOT EXISTS "revisionCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Work" ADD COLUMN IF NOT EXISTS "submittedAt" TIMESTAMP(3);
ALTER TABLE "Work" ADD COLUMN IF NOT EXISTS "approvedAt" TIMESTAMP(3);
ALTER TABLE "Work" ADD COLUMN IF NOT EXISTS "completedAt" TIMESTAMP(3);

-- CreateIndex
CREATE INDEX IF NOT EXISTS "Work_editorId_idx" ON "Work"("editorId");

-- AddForeignKey
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'Work_editorId_fkey'
    ) THEN
        ALTER TABLE "Work" ADD CONSTRAINT "Work_editorId_fkey" FOREIGN KEY ("editorId") REFERENCES "Employee"("id") ON DELETE SET NULL ON UPDATE CASCADE;
    END IF;
END $$;
