export interface PermissionItem {
  module: string;
  action: string;
}

export const ALL_STANDARD_MODULES = [
  "DASHBOARD",
  "LEADS",
  "CUSTOMERS",
  "FOLLOW_UP",
  "VISITS",
  "PROPOSALS",
  "PAYMENTS",
  "NOTIFICATIONS",
  "REPORTS",
  "SETTINGS",
  "ATTENDANCE",
  "LEAVE",
  "TASKS",
  "SALARY",
  "LOAN",
] as const;

export type StandardModule = typeof ALL_STANDARD_MODULES[number];

export const STANDARD_PERMISSIONS: { module: string; action: string; description: string }[] = [
  // DASHBOARD
  { module: "DASHBOARD", action: "VIEW", description: "Access main dashboard view" },
  { module: "DASHBOARD", action: "CARD_STATS", description: "View summary statistics cards" },
  { module: "DASHBOARD", action: "CARD_LEADS", description: "View leads and follow-up cards" },
  { module: "DASHBOARD", action: "CARD_VISITS", description: "View field visits overview card" },
  { module: "DASHBOARD", action: "CARD_WORK", description: "View SSM and task work card" },
  { module: "DASHBOARD", action: "CARD_PROPOSALS", description: "View pending proposals card" },
  { module: "DASHBOARD", action: "CARD_EMPLOYEES", description: "View team and employee card" },

  // LEADS
  { module: "LEADS", action: "VIEW", description: "View CRM leads and details" },
  { module: "LEADS", action: "CREATE", description: "Create new CRM leads" },
  { module: "LEADS", action: "EDIT", description: "Edit and update CRM leads" },
  { module: "LEADS", action: "DELETE", description: "Delete CRM leads" },
  { module: "LEADS", action: "CHANGE_STATUS", description: "Change lead stage and pipeline status" },
  { module: "LEADS", action: "EXPORT", description: "Export lead records and contact lists" },
  { module: "LEADS", action: "TAB_OVERVIEW", description: "View lead overview tab" },
  { module: "LEADS", action: "TAB_ACTIVITY", description: "View lead activity and communication tab" },
  { module: "LEADS", action: "TAB_TIMELINE", description: "View lead journey timeline" },
  { module: "LEADS", action: "TAB_HISTORY", description: "View lead status audit history" },

  // CUSTOMERS
  { module: "CUSTOMERS", action: "VIEW", description: "View customers and client directory" },
  { module: "CUSTOMERS", action: "CREATE", description: "Add new customer or client account" },
  { module: "CUSTOMERS", action: "EDIT", description: "Edit customer details and settings" },
  { module: "CUSTOMERS", action: "DELETE", description: "Remove customer accounts" },
  { module: "CUSTOMERS", action: "EXPORT", description: "Export customer master list" },
  { module: "CUSTOMERS", action: "TAB_OVERVIEW", description: "View customer details overview" },
  { module: "CUSTOMERS", action: "TAB_PLANS", description: "View customer active plan and quotas" },
  { module: "CUSTOMERS", action: "TAB_SCHEDULE", description: "View customer deliverable schedule" },

  // FOLLOW_UP
  { module: "FOLLOW_UP", action: "VIEW", description: "View follow-up schedules and logs" },
  { module: "FOLLOW_UP", action: "CREATE", description: "Log new follow-ups" },
  { module: "FOLLOW_UP", action: "EDIT", description: "Update existing follow-ups" },
  { module: "FOLLOW_UP", action: "DELETE", description: "Delete follow-ups" },

  // VISITS
  { module: "VISITS", action: "VIEW", description: "View scheduled client visits" },
  { module: "VISITS", action: "CREATE", description: "Schedule new client visits" },
  { module: "VISITS", action: "EDIT", description: "Start, complete, or update visits" },
  { module: "VISITS", action: "DELETE", description: "Cancel or delete visits" },

  // PROPOSALS
  { module: "PROPOSALS", action: "VIEW", description: "View quotes and proposals" },
  { module: "PROPOSALS", action: "CREATE", description: "Create new commercial proposal" },
  { module: "PROPOSALS", action: "EDIT", description: "Modify proposal pricing and terms" },
  { module: "PROPOSALS", action: "DELETE", description: "Delete or void proposals" },
  { module: "PROPOSALS", action: "SEND", description: "Send proposals via email/WhatsApp" },
  { module: "PROPOSALS", action: "DOWNLOAD", description: "Download proposal PDF documents" },

  // PAYMENTS
  { module: "PAYMENTS", action: "VIEW", description: "View client payments and invoices" },
  { module: "PAYMENTS", action: "CREATE", description: "Record incoming client payments" },
  { module: "PAYMENTS", action: "EDIT", description: "Update payment entries" },
  { module: "PAYMENTS", action: "DELETE", description: "Delete payment logs" },
  { module: "PAYMENTS", action: "EXPORT", description: "Export payment financial records" },

  // NOTIFICATIONS
  { module: "NOTIFICATIONS", action: "VIEW", description: "View notifications center" },
  { module: "NOTIFICATIONS", action: "SEND", description: "Broadcast push and in-app notifications" },
  { module: "NOTIFICATIONS", action: "DELETE", description: "Clear or delete notifications" },

  // REPORTS
  { module: "REPORTS", action: "VIEW", description: "View CRM and HRM analytical reports" },
  { module: "REPORTS", action: "EXPORT", description: "Export analytical reports and spreadsheets" },
  { module: "REPORTS", action: "DOWNLOAD", description: "Download report files" },

  // SETTINGS
  { module: "SETTINGS", action: "VIEW", description: "View account and app settings" },
  { module: "SETTINGS", action: "EDIT", description: "Modify account and app settings" },
  { module: "SETTINGS", action: "SETTING_PROFILE", description: "View and edit profile section" },
  { module: "SETTINGS", action: "SETTING_NOTIFICATIONS", description: "Configure notifications" },
  { module: "SETTINGS", action: "SETTING_INTEGRATIONS", description: "Manage third-party integrations" },
  { module: "SETTINGS", action: "SETTING_USERS", description: "Manage team and user permissions" },

  // ATTENDANCE
  { module: "ATTENDANCE", action: "VIEW", description: "View attendance status and history" },
  { module: "ATTENDANCE", action: "CREATE", description: "Punch in/out attendance" },
  { module: "ATTENDANCE", action: "EDIT", description: "Regularize or edit attendance" },
  { module: "ATTENDANCE", action: "DELETE", description: "Delete attendance logs" },

  // LEAVE
  { module: "LEAVE", action: "VIEW", description: "View leaves and requests" },
  { module: "LEAVE", action: "CREATE", description: "Apply for leaves and requests" },
  { module: "LEAVE", action: "EDIT", description: "Update leave details" },
  { module: "LEAVE", action: "DELETE", description: "Cancel or delete leave requests" },
  { module: "LEAVE", action: "APPROVE", description: "Approve submitted leave applications" },
  { module: "LEAVE", action: "REJECT", description: "Reject submitted leave applications" },

  // TASKS
  { module: "TASKS", action: "VIEW", description: "View assigned tasks" },
  { module: "TASKS", action: "CREATE", description: "Create new tasks" },
  { module: "TASKS", action: "EDIT", description: "Update task status and details" },
  { module: "TASKS", action: "DELETE", description: "Delete tasks" },

  // SALARY
  { module: "SALARY", action: "VIEW", description: "View salary slips and payroll" },
  { module: "SALARY", action: "DOWNLOAD", description: "Download salary slip PDFs" },

  // LOAN
  { module: "LOAN", action: "VIEW", description: "View loan advances" },
  { module: "LOAN", action: "CREATE", description: "Request loan advance" },
  { module: "LOAN", action: "APPROVE", description: "Approve employee loan requests" },
  { module: "LOAN", action: "REJECT", description: "Reject employee loan requests" },
];

export const ROLE_PERMISSION_DEFAULTS: Record<string, PermissionItem[]> = {
  SUPER_ADMIN: STANDARD_PERMISSIONS.map((p) => ({ module: p.module, action: p.action })),
  COMPANY_ADMIN: STANDARD_PERMISSIONS.map((p) => ({ module: p.module, action: p.action })),
  TELECALLER: [
    { module: "DASHBOARD", action: "VIEW" },
    { module: "DASHBOARD", action: "CARD_STATS" },
    { module: "DASHBOARD", action: "CARD_LEADS" },
    { module: "LEADS", action: "VIEW" },
    { module: "LEADS", action: "CREATE" },
    { module: "LEADS", action: "EDIT" },
    { module: "LEADS", action: "CHANGE_STATUS" },
    { module: "LEADS", action: "TAB_OVERVIEW" },
    { module: "LEADS", action: "TAB_ACTIVITY" },
    { module: "FOLLOW_UP", action: "VIEW" },
    { module: "FOLLOW_UP", action: "CREATE" },
    { module: "CUSTOMERS", action: "VIEW" },
    { module: "CUSTOMERS", action: "TAB_OVERVIEW" },
    { module: "SETTINGS", action: "VIEW" },
    { module: "SETTINGS", action: "SETTING_PROFILE" },
    { module: "SETTINGS", action: "SETTING_NOTIFICATIONS" },
  ],
  SALES_EXECUTIVE: [
    { module: "DASHBOARD", action: "VIEW" },
    { module: "DASHBOARD", action: "CARD_STATS" },
    { module: "DASHBOARD", action: "CARD_LEADS" },
    { module: "DASHBOARD", action: "CARD_VISITS" },
    { module: "LEADS", action: "VIEW" },
    { module: "LEADS", action: "CREATE" },
    { module: "LEADS", action: "EDIT" },
    { module: "LEADS", action: "CHANGE_STATUS" },
    { module: "LEADS", action: "TAB_OVERVIEW" },
    { module: "LEADS", action: "TAB_ACTIVITY" },
    { module: "LEADS", action: "TAB_TIMELINE" },
    { module: "FOLLOW_UP", action: "VIEW" },
    { module: "FOLLOW_UP", action: "CREATE" },
    { module: "FOLLOW_UP", action: "EDIT" },
    { module: "VISITS", action: "VIEW" },
    { module: "VISITS", action: "CREATE" },
    { module: "VISITS", action: "EDIT" },
    { module: "CUSTOMERS", action: "VIEW" },
    { module: "CUSTOMERS", action: "TAB_OVERVIEW" },
    { module: "PROPOSALS", action: "VIEW" },
    { module: "PROPOSALS", action: "CREATE" },
    { module: "TASKS", action: "VIEW" },
    { module: "TASKS", action: "EDIT" },
    { module: "SETTINGS", action: "VIEW" },
    { module: "SETTINGS", action: "SETTING_PROFILE" },
  ],
  HR: [
    { module: "DASHBOARD", action: "VIEW" },
    { module: "DASHBOARD", action: "CARD_STATS" },
    { module: "DASHBOARD", action: "CARD_EMPLOYEES" },
    { module: "ATTENDANCE", action: "VIEW" },
    { module: "ATTENDANCE", action: "CREATE" },
    { module: "ATTENDANCE", action: "EDIT" },
    { module: "ATTENDANCE", action: "DELETE" },
    { module: "LEAVE", action: "VIEW" },
    { module: "LEAVE", action: "CREATE" },
    { module: "LEAVE", action: "EDIT" },
    { module: "LEAVE", action: "DELETE" },
    { module: "LEAVE", action: "APPROVE" },
    { module: "LEAVE", action: "REJECT" },
    { module: "SALARY", action: "VIEW" },
    { module: "SETTINGS", action: "VIEW" },
    { module: "SETTINGS", action: "SETTING_PROFILE" },
    { module: "SETTINGS", action: "SETTING_NOTIFICATIONS" },
    { module: "SALARY", action: "DOWNLOAD" },
    { module: "REPORTS", action: "VIEW" },
    { module: "SETTINGS", action: "VIEW" },
    { module: "SETTINGS", action: "SETTING_PROFILE" },
  ],
  EMPLOYEE: [
    { module: "DASHBOARD", action: "VIEW" },
    { module: "DASHBOARD", action: "CARD_STATS" },
    { module: "ATTENDANCE", action: "VIEW" },
    { module: "ATTENDANCE", action: "CREATE" },
    { module: "LEAVE", action: "VIEW" },
    { module: "LEAVE", action: "CREATE" },
    { module: "TASKS", action: "VIEW" },
    { module: "TASKS", action: "EDIT" },
    { module: "SALARY", action: "VIEW" },
    { module: "VISITS", action: "VIEW" },
    { module: "SETTINGS", action: "VIEW" },
    { module: "SETTINGS", action: "SETTING_PROFILE" },
  ],
  MANAGER: [
    { module: "DASHBOARD", action: "VIEW" },
    { module: "DASHBOARD", action: "CARD_STATS" },
    { module: "DASHBOARD", action: "CARD_LEADS" },
    { module: "DASHBOARD", action: "CARD_VISITS" },
    { module: "DASHBOARD", action: "CARD_EMPLOYEES" },
    { module: "LEADS", action: "VIEW" },
    { module: "LEADS", action: "CREATE" },
    { module: "LEADS", action: "EDIT" },
    { module: "LEADS", action: "DELETE" },
    { module: "LEADS", action: "CHANGE_STATUS" },
    { module: "LEADS", action: "EXPORT" },
    { module: "CUSTOMERS", action: "VIEW" },
    { module: "CUSTOMERS", action: "CREATE" },
    { module: "CUSTOMERS", action: "EDIT" },
    { module: "FOLLOW_UP", action: "VIEW" },
    { module: "FOLLOW_UP", action: "CREATE" },
    { module: "FOLLOW_UP", action: "EDIT" },
    { module: "FOLLOW_UP", action: "DELETE" },
    { module: "VISITS", action: "VIEW" },
    { module: "VISITS", action: "CREATE" },
    { module: "VISITS", action: "EDIT" },
    { module: "VISITS", action: "DELETE" },
    { module: "ATTENDANCE", action: "VIEW" },
    { module: "ATTENDANCE", action: "CREATE" },
    { module: "ATTENDANCE", action: "EDIT" },
    { module: "LEAVE", action: "VIEW" },
    { module: "LEAVE", action: "CREATE" },
    { module: "LEAVE", action: "EDIT" },
    { module: "LEAVE", action: "APPROVE" },
    { module: "LEAVE", action: "REJECT" },
    { module: "TASKS", action: "VIEW" },
    { module: "TASKS", action: "CREATE" },
    { module: "TASKS", action: "EDIT" },
    { module: "REPORTS", action: "VIEW" },
    { module: "REPORTS", action: "EXPORT" },
    { module: "SETTINGS", action: "VIEW" },
    { module: "SETTINGS", action: "SETTING_PROFILE" },
  ],
};
