-- AlterEnum LeadStatus (Add missing enum values to PostgreSQL pg_enum)
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'CONVERTED';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'PROPOSAL_SENT';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'FINAL_CALL';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'PAYMENT';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'WORK_STARTED';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'CANCELLED';

-- AlterTable Lead (Add missing columns to Lead table)
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "country" TEXT;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "latitude" DOUBLE PRECISION;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "longitude" DOUBLE PRECISION;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "googlePlaceId" TEXT;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "rating" DOUBLE PRECISION;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "reviewCount" INTEGER;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "convertedToCompanyId" INTEGER;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "convertedToContactId" INTEGER;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "convertedToDealId" INTEGER;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "convertedAt" TIMESTAMP(3);
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "nextFollowUpTime" TEXT;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "workStartDate" TIMESTAMP(3);
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "workNotes" TEXT;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "assignedTeam" TEXT;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "paidAmount" DOUBLE PRECISION DEFAULT 0;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "paymentStatus" TEXT DEFAULT 'PENDING';
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "paymentMethod" TEXT;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "paymentRef" TEXT;

-- Create Index for googlePlaceId if not exists
CREATE INDEX IF NOT EXISTS "Lead_googlePlaceId_idx" ON "Lead"("googlePlaceId");
